---
- name: Installing Wordpress 
  hosts: webservers
  user: ubuntu
  become: yes
  gather_facts: false
  vars:
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - ansible_python_interpreter: python3
    # - setup:
    
  roles:
    - wordpress
    # - security
    