---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  
- name: Perform full patching
  package:
    name: '*'
    state: latest

- name: Remove undesirable packages
  package:
    name: "{{ unnecessary_software }}"
    state: absent

- name: Stop and disable unnecessary services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items: "{{ unnecessary_services }}"
  ignore_errors: yes

- name: Set a message of the day
  copy:
    dest: /etc/motd
    src: motd
    owner: root
    group: root
    mode: 0644

- name: Set a login banner
  copy:
    dest: "{{ item }}"
    src: issue
    owner: root
    group: root
    mode: 0644
  with_items:
    - /etc/issue
    - /etc/issue.net

### --------------------------------------------------------------------

- name: Install UFW 
  apt: 
    name: ufw 
    state: latest
  notify: Reload UFW

- name: UFW - Allow HTTP on port {{ http_port }}
  ufw:
    rule: allow
    port: "{{ http_port }}"
    proto: tcp

- name: UFW - Allow HTTPs on port {{ https_port }}
  ufw:
    rule: allow
    port: "{{ https_port }}"
    proto: tcp

- name: UFW - Allow Port {{ ssh_port }}
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp

- name: SSH Limiting 
  ufw:
    rule: limit
    port: ssh
    proto: tcp

### --------------------------------------------------------------------

- name: Add admin group
  group:
    name: admin
    state: present

- name: Add local user
  user:
    name: admin
    group: admin
    shell: /bin/bash
    home: /home/admin
    create_home: yes
    state: present

- name: Add SSH public key for user
  authorized_key:
    user: admin
    key: "{{ lookup('file', 'id_rsa.pub') }}"
    state: present

- name: Add sudoer rule for local user
  copy:
    dest: /etc/sudoers
    src: sudoers
    owner: root
    group: root
    mode: 0440
    validate: /usr/sbin/visudo -csf %s

- name: Add hardened SSH config "PermitRootLogin NO !"
  copy:
    dest: /etc/ssh/sshd_config
    src: sshd_config
    owner: root
    group: root
    mode: 0600
  notify: Reload SSH

### --------------------------------------------------------------------

# - name: Add permitted networks to internal zone
#   firewalld:
#     zone: internal
#     source: "{{ item }}"
#     state: enabled
#     immediate: yes
#     permanent: yes
#   with_items: "{{ allowed_ssh_networks }}"

