---
# Tasks for server
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=9600

- name: Install Required Server Packages
  apt:
    name:
      - apache2
      - mysql-server
      - python3-pymysql
      - php
      - php-mysql
      - libapache2-mod-php
      - python3-pip
      - libmysqlclient-dev
    state: latest
    update_cache: yes  

- name: Install Required PHP Extensions
  apt:
    name:
      - php-gd
      - php-ssh2
      - php-cli
      - php-cgi
      - php-fpm
      - php-curl
      - php-mbstring
      - php-xml
      - php-xmlrpc
      - php-soap
      - php-intl
      - php-zip
    state: latest
    update_cache: yes

# Tasks for MySQL

# - name: Sets the root password 
#   mysql_user: 
#     name: root 
#     password: "{{ mysql_root_password }}"
#     login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create mysql database
  mysql_db: 
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ wp_mysql_db }}" 
    state: present

- name: Create mysql user
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ wp_mysql_user }}"
    password: "{{ wp_mysql_password }}"
    priv: '*.*:ALL'

# Tasks for Wordpress

- name: Download WordPress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no

- name: Update default Apache site
  lineinfile:
    dest=/etc/apache2/sites-enabled/000-default.conf
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
  - restart apache
  - restart MySQL

- name: Rename sample config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php
    
- name: Update WordPress config file
  replace:
    path: /var/www/wordpress/wp-config.php
    regexp: "{{ item.regexp1 }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp1: 'database_name_here', replace: '{{wp_mysql_db}}'}
    - { regexp1: 'username_here', replace: '{{wp_mysql_user}}'}
    - { regexp1: 'password_here', replace: '{{wp_mysql_password}}'}