# handlers file for wordpress
- name: restart MySQL
  service: 
    name: mysql 
    state: started 
    enabled: yes

- name: restart Nginx
  service: 
    name: nginx 
    state: restarted 
    enabled: yes
  become: yes