# default security parameters
allowed_ssh_networks:
  - 102.45.12.119/24
  # - 10.10.10.0/24
unnecessary_services:
  - postfix
  - telnet
unnecessary_software:
  - tcpdump
  - nmap-ncat
  - wpa_supplicant